const catalogConfigs = {
  sizes: {
    key: 'sizes',
    table: 'sizes',
    idField: 'size_id',
    label: 'Size',
    hasCode: true,
    editableFields: ['name', 'sort_order', 'description', 'active'],
    orderBy: 'sort_order asc, name asc',
    selectColumns: [
      'size_id',
      'code',
      'name',
      'sort_order',
      'description',
      'active',
      'created_at',
      'updated_at',
    ],
  },
  colors: {
    key: 'colors',
    table: 'colors',
    idField: 'color_id',
    label: 'Color',
    hasCode: true,
    editableFields: ['name', 'hex', 'active'],
    orderBy: 'name asc',
    selectColumns: [
      'color_id',
      'code',
      'name',
      'hex',
      'active',
      'created_at',
      'updated_at',
    ],
  },
  'garment-types': {
    key: 'garment-types',
    table: 'garment_types',
    idField: 'garment_type_id',
    label: 'Garment type',
    hasCode: true,
    editableFields: ['name', 'active'],
    orderBy: 'name asc',
    selectColumns: [
      'garment_type_id',
      'code',
      'name',
      'active',
      'created_at',
      'updated_at',
    ],
  },
  fabrics: {
    key: 'fabrics',
    table: 'fabrics',
    idField: 'fabric_id',
    label: 'Fabric',
    hasCode: true,
    editableFields: ['name', 'active'],
    orderBy: 'name asc',
    selectColumns: [
      'fabric_id',
      'code',
      'name',
      'active',
      'created_at',
      'updated_at',
    ],
  },
  'fabric-details': {
    key: 'fabric-details',
    table: 'fabric_details',
    idField: 'fabric_detail_id',
    label: 'Fabric detail',
    hasCode: true,
    editableFields: ['name', 'active'],
    orderBy: 'name asc',
    selectColumns: [
      'fabric_detail_id',
      'code',
      'name',
      'active',
      'created_at',
      'updated_at',
    ],
  },
  targets: {
    key: 'targets',
    table: 'targets',
    idField: 'target_id',
    label: 'Target',
    hasCode: false,
    editableFields: ['active'],
    orderBy: 'name asc',
    selectColumns: [
      'target_id',
      'name',
      'active',
      'created_at',
      'updated_at',
    ],
  },
};

function getCatalogConfig(key) {
  return catalogConfigs[key] || null;
}

module.exports = {
  catalogConfigs,
  getCatalogConfig,
};
